name: workout reminder

on:
  # schedule:
    # Runs "At 15:29 on every day-of-week from Monday through Friday." (see https://crontab.guru)
   # - cron:  '20 7 * * 1-5'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  webhook-call:
    runs-on: ubuntu-latest
    steps:
      - name: show date
        run: date
      - name: cURL request
        run: |
          curl --request POST \
          --url https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.ENT_BOT_TOKEN }} \
          --header 'content-type: application/json' \
          --data '{
              "msgtype": "text",
              "text": {
                 "content": "⏰运动时间到了～， 各位准备活动一下吧"
              }
            }'
